(function(d){var h=[];d.loadImages=function(a,e){"string"==typeof a&&(a=[a]);for(var f=a.length,g=0,b=0;b<f;b++){var c=document.createElement("img");c.onload=function(){g++;g==f&&d.isFunction(e)&&e()};c.src=a[b];h.push(c)}}})(window.jQuery);
var wl;

var lwi=-1;function thresholdPassed(){var w=$(window).width();var p=false;var cw=0;if(w>=480){cw++;}if(w>=768){cw++;}if(w>=960){cw++;}if(w>=1200){cw++;}if(lwi!=cw){p=true;}lwi=cw;return p;}
!function(){if("Promise"in window){var e,t,r=document,n=function(){return r.createElement("link")},o=new Set,a=n(),i=a.relList&&a.relList.supports&&a.relList.supports("prefetch"),s=location.href.replace(/#[^#]+$/,"");o.add(s);var c=function(e){var t=location,r="http:",n="https:";if(e&&e.href&&e.origin==t.origin&&[r,n].includes(e.protocol)&&(e.protocol!=r||t.protocol!=n)){var o=e.pathname;if(!(e.hash&&o+e.search==t.pathname+t.search||".html"!=o.substr(-5)&&".html"!=o.substr(-5)&&"/"!=o.substr(-1)))return!0}},u=function(e){var t=e.replace(/#[^#]+$/,"");if(!o.has(t)){if(i){var a=n();a.rel="prefetch",a.href=t,r.head.appendChild(a)}else{var s=new XMLHttpRequest;s.open("GET",t,s.withCredentials=!0),s.send()}o.add(t)}},f=function(e){return e.target.closest("a")},p=function(t){var r=t.relatedTarget;r&&f(t)==r.closest("a")||e&&(clearTimeout(e),e=void 0)},l={capture:!0,passive:!0};r.addEventListener("touchstart",function(e){t=performance.now();var r=f(e);c(r)&&u(r.href)},l),r.addEventListener("mouseover",function(r){if(!(performance.now()-t<1200)){var n=f(r);c(n)&&(n.addEventListener("mouseout",p,{passive:!0}),e=setTimeout(function(){u(n.href),e=void 0},80))}},l)}}();

$(function(){
r=function(){if(thresholdPassed()){dpi=window.devicePixelRatio;if($(window).width()>=1200){var e=document.querySelector('.js1');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/wayout_logo-1533.png':'images/wayout_logo-1022.png'):'images/wayout_logo-511.png');
var a='data-src';var e=document.querySelector('.js2 .slide0');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/dji_0132-2100.jpg':'images/dji_0132-1400.jpg'):'images/dji_0132-700.jpg');
var a='data-src';var e=document.querySelector('.js2 .slide1');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/dji_0074-2100.jpg':'images/dji_0074-1400.jpg'):'images/dji_0074-700.jpg');
var a='data-src';var e=document.querySelector('.js2 .slide2');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/dji_0111-2100.jpg':'images/dji_0111-1400.jpg'):'images/dji_0111-700.jpg');
var a='data-src';var e=document.querySelector('.js2 .slide3');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/dji_0057-2100.jpg':'images/dji_0057-1400.jpg'):'images/dji_0057-700.jpg');}else if($(window).width()>=960){var e=document.querySelector('.js1');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/wayout_logo-1227.png':'images/wayout_logo-818.png'):'images/wayout_logo-409.png');
var a='data-src';var e=document.querySelector('.js2 .slide0');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/dji_0132-1680.jpg':'images/dji_0132-1120.jpg'):'images/dji_0132-560-1.jpg');
var a='data-src';var e=document.querySelector('.js2 .slide1');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/dji_0074-1680.jpg':'images/dji_0074-1120.jpg'):'images/dji_0074-560-1.jpg');
var a='data-src';var e=document.querySelector('.js2 .slide2');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/dji_0111-1680.jpg':'images/dji_0111-1120.jpg'):'images/dji_0111-560-1.jpg');
var a='data-src';var e=document.querySelector('.js2 .slide3');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/dji_0057-1680.jpg':'images/dji_0057-1120.jpg'):'images/dji_0057-560-1.jpg');}else if($(window).width()>=768){var e=document.querySelector('.js1');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/wayout_logo-981.png':'images/wayout_logo-654.png'):'images/wayout_logo-327.png');
var a='data-src';var e=document.querySelector('.js2 .slide0');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/dji_0132-1344.jpg':'images/dji_0132-896.jpg'):'images/dji_0132-448.jpg');
var a='data-src';var e=document.querySelector('.js2 .slide1');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/dji_0074-1344.jpg':'images/dji_0074-896.jpg'):'images/dji_0074-448.jpg');
var a='data-src';var e=document.querySelector('.js2 .slide2');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/dji_0111-1344.jpg':'images/dji_0111-896.jpg'):'images/dji_0111-448.jpg');
var a='data-src';var e=document.querySelector('.js2 .slide3');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/dji_0057-1344.jpg':'images/dji_0057-896.jpg'):'images/dji_0057-448.jpg');}else if($(window).width()>=480){var e=document.querySelector('.js1');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/wayout_logo-612.png':'images/wayout_logo-408.png'):'images/wayout_logo-204.png');
var a='data-src';var e=document.querySelector('.js2 .slide0');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/dji_0132-840.jpg':'images/dji_0132-560.jpg'):'images/dji_0132-280.jpg');
var a='data-src';var e=document.querySelector('.js2 .slide1');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/dji_0074-840.jpg':'images/dji_0074-560.jpg'):'images/dji_0074-280.jpg');
var a='data-src';var e=document.querySelector('.js2 .slide2');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/dji_0111-840.jpg':'images/dji_0111-560.jpg'):'images/dji_0111-280.jpg');
var a='data-src';var e=document.querySelector('.js2 .slide3');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/dji_0057-840.jpg':'images/dji_0057-560.jpg'):'images/dji_0057-280.jpg');}else{var e=document.querySelector('.js1');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/wayout_logo-411.png':'images/wayout_logo-274.png'):'images/wayout_logo-137.png');
var a='data-src';var e=document.querySelector('.js2 .slide0');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/dji_0132-561.jpg':'images/dji_0132-374.jpg'):'images/dji_0132-187.jpg');
var a='data-src';var e=document.querySelector('.js2 .slide1');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/dji_0074-561.jpg':'images/dji_0074-374.jpg'):'images/dji_0074-187.jpg');
var a='data-src';var e=document.querySelector('.js2 .slide2');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/dji_0111-561.jpg':'images/dji_0111-374.jpg'):'images/dji_0111-187.jpg');
var a='data-src';var e=document.querySelector('.js2 .slide3');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/dji_0057-561.jpg':'images/dji_0057-374.jpg'):'images/dji_0057-187.jpg');}}};
if(!window.HTMLPictureElement){$(window).resize(r);r();}
(function(){$('a[href^="#"]:not(.allowConsent,.noConsent,.denyConsent,.removeConsent)').each(function(i,e){$(e).click(function(){var t=e.hash.length>1?$('[name="'+e.hash.slice(1)+'"]').offset().top:0;return $("html, body").animate({scrollTop:t},400),!1})})})();
initMenu($('#m1')[0]);
$('.js2 .slider').slick({lazyLoad: 'ondemand',slidesToShow: 1,slidesToScroll: 1,overflow: 'hidden',fade: true,slide: 'div',cssEase: 'linear',speed: 300,dots: false,arrows: false,infinite: true,autoplay: true,pauseOnHover: false,autoplaySpeed: 2500});
});